name: Build, Test & SonarQube

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  pull-requests: read

jobs:

  build:
    name: Build, Test & SonarQube Analysis
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven

      - name: Check Java Version
        run: java -version

      - name: Check Maven Version
        run: mvn -version

      - name: Maven Clean
        run: mvn clean

      - name: Maven Compile
        run: mvn compile

      - name: Run Unit Tests
        run: mvn test

      - name: Maven Package
        run: mvn package -DskipTests

      - name: Cache SonarQube Packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: |
            ${{ runner.os }}-sonar

      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn verify \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=patraasish_BlogApp \
            -Dsonar.qualitygate.wait=true

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: blogapp-jar
          path: target/*.jar